### ISSUE TITLE
Bonus staking rewards not handled

### ISSUE THREAD

**Issue by slycrel** [geldmacher/Cake-to-CoinTracking-Converter#12]
Here is the line.  I'll change this manually in my import file for now.  Thank you for this tool, saved me a few hours of writing my own.  :)

`2021-05-03T22:08:04-06:00,Entry staking wallet: Signup bonus,5.06995267,DFI,20,USD,,,7d02bf46-62c3-4307-a40b-a8afcd81e90d,`

**Comment by geldmacher** [comment]
Thx! =) I will add this in the next version.

**Comment by geldmacher** [comment]
https://github.com/geldmacher/Cake-to-CoinTracking-Converter/releases/tag/v5.1.0
