### ISSUE TITLE
Some transactions that cannot be processed

### ISSUE THREAD

**Issue by RadioSteve-dev** [geldmacher/Cake-to-CoinTracking-Converter#2]
First of all, thanks for the good work. The tool worked on my Windows machine like a charm. There were only a few transactions that could not be processed and I had to add them manually to Cointracking...

BTC Cannot Process:
Claimed for 50% discount 
Referral reward 

DFI Cannot Process:
Referral signup bonus 
Signup bonus 
Used for 50% discount 
Confectionery Lending DFI Bonus

("Claimed and Used for 50% discount," is of course 1 TRADE)

Keep the good work!

**Comment by geldmacher** [comment]
Thank you! :)

Could you post the lines from the Cake CSV which are missing? You can change the numbers and dates if you wish to. I do not have this kind of data in my own exports.

**Comment by RadioSteve-dev** [comment]
Welcome! Yes, of course...

BTC csv:
"2021-04-11T20:00:00-04:00","Referral reward","0.00000478","BTC","0.288133634954357256","USD","","","32d56ff5-df2d-4149-a2a5-964763d6170d",""
"2021-01-15T16:08:42-03:00","Claimed for 50% discount","0.85565778","BTC","30196.862966972939948984","USD","","","2775a9f9-8876-40ed-abcb-b77b9dd60acf","d7046889-9d3c-4da5-8c78-cef14bf93d9e"

DFI csv:
"2021-02-08T17:27:58-03:00","Referral signup bonus","3.04878048","DFI","10","USD","","","5edd955a-3443-4f78-b543-b21bb2ea6451",""
"2020-12-20T09:31:55-03:00","Signup bonus","29.92708266","DFI","20","USD","","","a9439fec-5f80-40c0-b0b7-c3d36e023710",""
"2021-01-15T16:08:42-03:00","Used for 50% discount","-6003.59124991","DFI","-15098.431634398659","USD","","","d7046889-9d3c-4da5-8c78-cef14bf93d9e",""
"2021-01-15T07:04:31-03:00","Confectionery Lending DFI Bonus","2191.34523464","DFI","5920.0506320940384","USD","","","c16de463-fc92-4a51-b218-e4393793486b",""

Good luck!

**Comment by geldmacher** [comment]
@RadioSteve-dev Low hanging fruits first: https://github.com/geldmacher/Cake-to-CoinTracking-Converter/releases/tag/v3.1.0

Please give me some feedback if this works for you. I will integrate the missing (more complicated) operations next time. 

Still missing:
- Claimed for 50% discount
- Used for 50% discount

**Comment by RadioSteve-dev** [comment]
@geldmacher Thanks for perfectly harvesting the "low hanging fruits." Worked perfectly!

**Comment by geldmacher** [comment]
@RadioSteve-dev I am not quite sure how to import the claming operations into CoinTracking. If i understand the process correctly yout paid DFI worth of round about 15k USD to get BTC worth of round about 30k, right?

I am no tax pro and i am not doing this kind of operations at Cake. So perhaps we should discuss how you would like this to be imported into CoinTracking!? My approach would be:

1) Import a normal trade from all the DFI to 50% of theBTC
2) Import a bonus income for the other 50% of BTC

But the last one would be a taxable income. So it might be better to declare 2) as an non-taxable income. But i am not sure if this approach would be accepted by your tax authority ... ;)

What do you think?

**Comment by RadioSteve-dev** [comment]
@geldmacher Hi Dennis, I am not sure neither about that. I booked it manually as 1 trade, what it was indeed. So, Cointracking has to decide how to handle that and not we. My rax authority does not tax me on crypto anyway because I live in Paraguay. But I do that in case the law would change one day, and to have the nice statistics and overview CoinTracking provides. So, no problem, if you do not implement this!

**Comment by RadioSteve-dev** [comment]
@geldmacher Hi Dennis, works like a charm. Thank you very much!
