### ISSUE TITLE
CoinTrackin now has its own Cake DFI CSV Importer

### ISSUE THREAD

**Issue by dnltsk** [geldmacher/Cake-to-CoinTracking-Converter#8]
This Project helped me a lot in the early days ❤️  But as time passes by - it seems to become obsolete.
See https://cointracking.info/import/cakedefi

**Comment by geldmacher** [comment]
I haven't checked it for a few weeks now. The last time i did their importer wasn't capable of importing LM transactions. Is it working now?

**Comment by dnltsk** [comment]
Yes, it's working as expected. You will get duplicates when importing the CSVs by both importers. The Exchange name changes from "Cake" to "Cake DEFI" for example.

**Comment by geldmacher** [comment]
Thanks, will give it a try!
